"""Schema mapping module for transforming source columns to target schema."""

import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd
import yaml
from rapidfuzz import fuzz

from src.extract.source_registry import SourceConfig, SourceRegistry
from src.transform.normalizers import (
    AddressNormalizer,
    AgeParser,
    CapacityNormalizer,
    LicenseStatusNormalizer,
    NameNormalizer,
    PhoneNormalizer,
    StateNormalizer,
    ZipNormalizer,
)
from src.utils.hashing import compute_schema_fingerprint
from src.utils.logging_config import get_logger

logger = get_logger(__name__)


class SchemaMapper:
    """Maps source data columns to target schema with rule-based and AI-assisted mapping."""

    # Target schema columns
    TARGET_COLUMNS = [
        "company",
        "facility_type",
        "address1",
        "address2",
        "city",
        "state",
        "zip",
        "county",
        "phone",
        "phone2",
        "email",
        "website_address",
        "first_name",
        "last_name",
        "capacity",
        "min_age",
        "max_age",
        "ages_served",
        "license_status",
        "license_number",
        "license_type",
    ]

    def __init__(
        self,
        source_registry: Optional[SourceRegistry] = None,
        llm_client: Optional[Any] = None,
        use_ai_mapping: bool = True,
        logic_file: Optional[Path] = Path("config/logic.yaml"),
    ):
        """
        Initialize the schema mapper.

        Args:
            source_registry: Registry of known source configurations
            llm_client: LLM client for AI-assisted mapping
            use_ai_mapping: Whether to use AI for unknown schemas
            logic_file: Path to YAML file with business logic rules
        """
        self.source_registry = source_registry or SourceRegistry()
        self.llm_client = llm_client
        self.use_ai_mapping = use_ai_mapping
        self._mapping_cache: Dict[str, Dict[str, str]] = {}

        # Initialize normalizers
        self.normalizers = {
            "phone": PhoneNormalizer(),
            "state": StateNormalizer(),
            "zip": ZipNormalizer(),
            "address": AddressNormalizer(),
            "name": NameNormalizer(),
            "age": AgeParser(),
            "capacity": CapacityNormalizer(),
            "license_status": LicenseStatusNormalizer(),
        }

        # Load business logic from YAML
        # `default_business_logic` and `default_logic_settings` are loaded from
        # the YAML config file. `schema_business_logic` and
        # `schema_logic_settings` store per-schema (fingerprint) logic that may
        # be generated by the LLM during mapping.
        self.default_business_logic = {}
        self.default_logic_settings = {}
        self.schema_business_logic: Dict[str, Dict] = {}
        self.schema_logic_settings: Dict[str, Dict] = {}
        if logic_file:
            self.load_business_logic(logic_file)

    def load_business_logic(self, yaml_file: Path):
        """Load transformations and business logic from a YAML file."""
        if not yaml_file.exists():
            logger.warning(f"Business logic YAML file {yaml_file} not found")
            self.business_logic = {}
            self.logic_settings = {}
            return

        try:
            with open(yaml_file, "r") as f:
                data = yaml.safe_load(f) or {}

            # Keep these as the default/global rules. Schema-specific logic
            # will be stored in `self.schema_business_logic` keyed by schema
            # fingerprint and will fall back to these defaults when absent.
            self.default_business_logic = data.get("transformations", {})
            self.default_logic_settings = data.get("settings", {})

            logger.info(
                f"Loaded {len(self.business_logic)} business logic rules from {yaml_file}"
            )
        except Exception as e:
            logger.error(f"Failed to load business logic from {yaml_file}: {e}")
            self.business_logic = {}
            self.logic_settings = {}

    def map_dataframe(
        self,
        df: pd.DataFrame,
        source_file: Path,
        source_config: Optional[SourceConfig] = None,
    ) -> pd.DataFrame:
        """
        Map a source DataFrame to the target schema.

        Args:
            df: Source DataFrame
            source_file: Path to source file (for metadata)
            source_config: Optional pre-determined source configuration

        Returns:
            DataFrame mapped to target schema
        """
        logger.info(f"Mapping {len(df)} rows from {source_file.name}")

        # Get source configuration
        if source_config is None:
            source_config = self.source_registry.get_source_for_file(source_file)

        # Determine column mapping
        if False:
            # if source_config and source_config.column_map:
            column_mapping = self._apply_rule_mapping(df, source_config)
        else:
            column_mapping = self._infer_mapping(df)

        logger.debug(f"Column mapping: {column_mapping}")

        # Create target DataFrame
        result = pd.DataFrame()

        # Apply mappings and transformations
        for target_col in self.TARGET_COLUMNS:
            if target_col in column_mapping:
                source_col = column_mapping[target_col]
                result[target_col] = self._transform_column(
                    df, source_col, target_col, source_config
                )

            result[target_col] = self._apply_yaml_rules(df, None, target_col)

        # Add metadata columns
        result["source_file"] = source_file.name
        result["record_id"] = self._generate_record_ids(df, source_file)

        logger.info(
            f"Mapped to {len(result)} rows with {len(self.TARGET_COLUMNS)} columns"
        )

        return result

    def _apply_rule_mapping(
        self, df: pd.DataFrame, source_config: SourceConfig
    ) -> Dict[str, str]:
        """Apply rule-based column mapping from source configuration."""
        mapping = {}

        for key, value in source_config.column_map.items():
            # Handle different config structures:
            # 1. Specific source: {source_col: target_col} (both strings)
            # 2. Default patterns: {target_col: [possible_names]} (list of patterns)

            if isinstance(value, list):
                # Default patterns structure: key is target_col, value is list of patterns
                target_col = key
                possible_names = value

                # Find matching column in dataframe
                for df_col in df.columns:
                    df_col_lower = df_col.lower().strip()
                    for pattern in possible_names:
                        if (
                            pattern.lower() in df_col_lower
                            or df_col_lower == pattern.lower()
                        ):
                            mapping[target_col] = df_col
                            break
                    if target_col in mapping:
                        break

            elif isinstance(value, str):
                # Specific source structure: key is source_col, value is target_col
                source_col = key
                target_col = value

                # Handle special transformation directives
                if target_col.startswith("_"):
                    continue  # Will be handled during transformation

                # Find matching column in dataframe (case-insensitive)
                for df_col in df.columns:
                    if df_col.lower().strip() == source_col.lower().strip():
                        mapping[target_col] = df_col
                        break

        return mapping

    def _infer_mapping(self, df: pd.DataFrame) -> Dict[str, str]:
        """
        Infer column mapping using fuzzy matching or AI.

        Args:
            df: Source DataFrame

        Returns:
            Column mapping dictionary
        """
        # Check cache first
        schema_fingerprint = compute_schema_fingerprint(list(df.columns))
        if schema_fingerprint in self._mapping_cache:
            logger.debug(f"Using cached mapping for schema {schema_fingerprint}")
            return self._mapping_cache[schema_fingerprint]

        # Try fuzzy matching
        mapping = self._fuzzy_match_mapping(df)

        # If AI mapping is enabled and we have an LLM client, use it
        if (
            self.use_ai_mapping
            and self.llm_client
            and len(mapping) < len(self.TARGET_COLUMNS) / 2
        ):
            ai_mapping = self._ai_assisted_mapping(df)
            mapping.update(ai_mapping)

        # If we have an LLM available and no schema-specific logic exists yet,
        # ask the LLM to generate business logic for this schema and store it.
        if self.llm_client and schema_fingerprint not in self.schema_business_logic:
            try:
                self._generate_schema_logic(schema_fingerprint, df, mapping)
            except Exception:
                logger.debug("Failed to generate schema logic via LLM; continuing")

        # Cache the result
        self._mapping_cache[schema_fingerprint] = mapping

        return mapping

    def _fuzzy_match_mapping(self, df: pd.DataFrame) -> Dict[str, str]:
        """Fuzzy match source columns to target columns."""
        mapping = {}

        # Get default patterns
        default_config = self.source_registry.default_config
        if not default_config or not default_config.column_map:
            return mapping

        patterns = default_config.column_map
        threshold = 0.85

        for target_col, possible_names in patterns.items():
            best_match = None
            best_score = 0

            for source_col in df.columns:
                source_lower = source_col.lower().strip()

                # Direct match
                if source_lower == target_col.lower():
                    best_match = source_col
                    best_score = 1.0
                    break

                # Check against patterns
                for pattern in possible_names:
                    score = fuzz.ratio(source_lower, pattern.lower()) / 100
                    if score > best_score and score >= threshold:
                        best_match = source_col
                        best_score = score

            if best_match:
                mapping[target_col] = best_match

        return mapping

    def _ai_assisted_mapping(self, df: pd.DataFrame) -> Dict[str, str]:
        """Use LLM to infer column mapping for unknown schemas."""
        if not self.llm_client:
            return {}

        try:
            # Get sample data
            sample_data = df.sample(min(5, len(df))).to_dict(orient="records")

            # Build prompt
            prompt = self._build_schema_mapping_prompt(list(df.columns), sample_data)

            # Call LLM
            response = self.llm_client.complete(prompt)

            # Parse response
            mapping = self._parse_llm_mapping_response(response)

            logger.info(f"AI-assisted mapping inferred {len(mapping)} columns")
            return mapping

        except Exception as e:
            logger.warning(f"AI-assisted mapping failed: {e}")
            return {}

    def _build_schema_logic_prompt(
        self,
        source_columns: List[str],
        sample_data: List[Dict],
        mapping: Dict[str, str],
    ) -> str:
        """Build prompt asking the LLM to produce YAML business logic for the schema.

        The LLM should return YAML with top-level `transformations` and optional
        `settings`. Each transformation should be a mapping of rule name to a
        dict containing `target_column`, `source_column`, and one of `regex`,
        `condition`/`value`, or `mapping`.
        """

        prompt = f"""
You are a data engineering assistant. Given the following source CSV columns and small sample of data, generate a YAML configuration that defines transformation rules for mapping source columns to the standardized target schema.

Source columns:
{chr(10).join(f"- {c}" for c in source_columns)}

Sample data (up to 5 rows):
{sample_data}

Known inferred mappings (target_column -> source_column):
{mapping}

Return YAML only. The YAML should have:
- `transformations`: mapping of rule name -> rule, where each rule contains:
  - `target_column`: the target field name
  - `source_column`: the source column name
  - and one of:
    - `regex`: a regex to extract a component (use `format` to build output)
    - `condition` and `value`: to set a value when the condition matches
    - `mapping`: a dict mapping source values to target values
- `settings` (optional): case_sensitive, skip_empty_values, log_unmatched_rules

Keep rules concise and only include rules that appear useful for this schema. Use realistic regexes where applicable. Example rule:

transformations:
  phone_rule:
    target_column: phone
    source_column: phone_number
    regex: "(\\d{3}[- ]?\\d{3}[- ]?\\d{4})"

Return the YAML block only.
"""

        return prompt

    def _parse_llm_logic_response(self, response: str) -> Tuple[Dict, Dict]:
        """Attempt to parse YAML from LLM response. Returns (transformations, settings)."""
        # Try to extract fenced code block first
        yaml_text = None
        fenced = re.search(
            r"```(?:yaml|yml)?\n(.*)```", response, re.DOTALL | re.IGNORECASE
        )
        if fenced:
            yaml_text = fenced.group(1)
        else:
            # Try to find 'transformations:' start
            m = re.search(r"transformations:\s", response)
            if m:
                yaml_text = response[m.start() :]

        if not yaml_text:
            # As a last resort, try to load entire response
            yaml_text = response

        try:
            parsed = yaml.safe_load(yaml_text) or {}
            return parsed.get("transformations", {}), parsed.get("settings", {})
        except Exception:
            logger.warning("Could not parse LLM logic response as YAML")
            return {}, {}

    def _generate_schema_logic(
        self, schema_fingerprint: str, df: pd.DataFrame, mapping: Dict[str, str]
    ):
        """Generate and store schema-specific business logic using the LLM.

        The generated logic is stored in `self.schema_business_logic` and any
        settings in `self.schema_logic_settings` keyed by `schema_fingerprint`.
        """
        if not self.llm_client:
            return

        sample_data = df.sample(min(5, len(df))).to_dict(orient="records")
        prompt = self._build_schema_logic_prompt(list(df.columns), sample_data, mapping)

        try:
            response = self.llm_client.complete(prompt)
            transformations, settings = self._parse_llm_logic_response(response)

            if transformations:
                self.schema_business_logic[schema_fingerprint] = transformations
                self.schema_logic_settings[schema_fingerprint] = settings
                logger.info(
                    f"Stored {len(transformations)} schema rules for {schema_fingerprint}"
                )
        except Exception as e:
            logger.warning(f"Failed to generate schema logic: {e}")

    def _build_schema_mapping_prompt(
        self, source_columns: List[str], sample_data: List[Dict]
    ) -> str:
        """Build prompt for schema mapping LLM call."""
        target_descriptions = {
            "company": "Facility/business name",
            "facility_type": "Type of facility (center, family care, etc.)",
            "address1": "Street address line 1",
            "address2": "Street address line 2 (apt, suite, etc.)",
            "city": "City name",
            "state": "State abbreviation (2-letter)",
            "zip": "ZIP code (5-digit)",
            "county": "County name",
            "phone": "Primary phone number",
            "phone2": "Secondary phone number",
            "email": "Email address",
            "website_address": "Website URL",
            "first_name": "Contact person first name",
            "last_name": "Contact person last name",
            "capacity": "Maximum number of children",
            "min_age": "Minimum age served (in years)",
            "max_age": "Maximum age served (in years)",
            "ages_served": "Original age range description",
            "license_status": "License status (Active/Inactive/Expired/etc.)",
            "license_number": "License/credential number",
            "license_type": "Type of license",
        }

        prompt = f"""You are a data engineering assistant. Given the following source CSV columns and sample data, map each source column to the most appropriate target column from the standardized schema.

TARGET SCHEMA COLUMNS:
{chr(10).join(f"- {col}: {desc}" for col, desc in target_descriptions.items())}

SOURCE COLUMNS:
{chr(10).join(f"- {col}" for col in source_columns)}

SAMPLE DATA (first 3 rows):
{sample_data[:3]}

Rules:
- Map each source column to exactly one target column, or mark as "EXCLUDE" if not useful
- If a source column contains combined data (e.g., full address), mark for special handling with "PARSE_" prefix
- Return your answer as a JSON object where keys are target columns and values are source columns

Return format:
{{
  "mappings": {{
    "target_column": "source_column",
    ...
  }},
  "confidence": 0.0-1.0,
  "notes": "any important observations"
}}"""

        return prompt

    def _parse_llm_mapping_response(self, response: str) -> Dict[str, str]:
        """Parse LLM response to extract column mappings."""
        import json

        try:
            # Try to find JSON in the response
            json_match = re.search(r"\{.*\}", response, re.DOTALL)
            if json_match:
                data = json.loads(json_match.group())
                return data.get("mappings", {})
        except json.JSONDecodeError:
            logger.warning("Could not parse LLM response as JSON")

        return {}

    def _transform_column(
        self,
        df: pd.DataFrame,
        source_col: str,
        target_col: str,
        source_config: Optional[SourceConfig],
    ) -> pd.Series:
        """Transform a source column to the target format."""
        if source_col not in df.columns:
            return pd.Series([None] * len(df))

        values = df[source_col].copy()

        # First, apply YAML business logic rules
        values = self._apply_yaml_rules(df, source_col, target_col, values)

        # Then apply built-in normalizers
        if target_col == "phone":
            values = values.apply(lambda x: self.normalizers["phone"].normalize(x)[0])

        elif target_col == "state":
            values = values.apply(lambda x: self.normalizers["state"].normalize(x)[0])

        elif target_col == "zip":
            values = values.apply(lambda x: self.normalizers["zip"].normalize(x)[0])

        elif target_col == "license_status":
            values = values.apply(
                lambda x: self.normalizers["license_status"].normalize(x)[0]
            )

        elif target_col == "capacity":
            values = values.apply(
                lambda x: self.normalizers["capacity"].normalize(x)[0]
            )

        elif target_col in ["first_name", "last_name"]:
            # Handle contact name parsing
            values = values.apply(lambda x: self._extract_name_part(x, target_col))

        elif target_col in ["min_age", "max_age", "ages_served"]:
            values = values.apply(lambda x: self._extract_age_part(x, target_col))

        elif target_col in ["address1", "address2", "city"] and source_config:
            # Check if we need to parse combined address
            values = self._parse_address_column(
                df, source_col, target_col, source_config
            )

        else:
            # Default: return with basic cleaning
            values = values.apply(self._basic_clean)

        return values

    def _apply_yaml_rules(
        self,
        df: pd.DataFrame,
        source_col: Optional[str],
        target_col: str,
        values: Optional[pd.Series] = None,
    ) -> pd.Series:
        """Apply YAML business logic rules to transform column values."""
        # If no values provided, start with empty series
        if values is None:
            values = pd.Series([None] * len(df))

        # Determine schema fingerprint for this dataframe and select rules
        schema_fingerprint = compute_schema_fingerprint(list(df.columns))
        rules = self.schema_business_logic.get(
            schema_fingerprint, self.default_business_logic
        )
        settings = self.schema_logic_settings.get(
            schema_fingerprint, self.default_logic_settings
        )

        # Get settings (with defaults)
        case_sensitive = settings.get("case_sensitive", False)
        skip_empty = settings.get("skip_empty_values", True)
        log_unmatched = settings.get("log_unmatched_rules", False)

        # Apply each rule that matches this target column
        for rule_name, rule in rules.items():
            rule_target = rule.get("target_column")
            rule_source = rule.get("source_column")

            # Skip if rule doesn't apply to this target column
            if rule_target != target_col:
                continue

            # Get source data for this rule
            if rule_source and rule_source in df.columns:
                source_data = df[rule_source]
            elif source_col and source_col in df.columns:
                source_data = df[source_col]
            else:
                if log_unmatched:
                    logger.debug(
                        f"Rule '{rule_name}' skipped: source column '{rule_source}' not found"
                    )
                continue

            # Apply rule type
            if "regex" in rule:
                # Regex extraction
                pattern = re.compile(
                    rule["regex"], flags=0 if case_sensitive else re.IGNORECASE
                )

                def extract_regex(x):
                    if pd.isna(x) or (skip_empty and str(x).strip() == ""):
                        return None
                    match = pattern.search(str(x))
                    if match:
                        # If format specified, apply it
                        if "format" in rule:
                            try:
                                return match.expand(rule["format"])
                            except:
                                return match.group(0)
                        return match.group(1) if match.groups() else match.group(0)
                    return None

                extracted = source_data.apply(extract_regex)
                # Only update non-null values
                values = values.fillna(extracted)

            elif "condition" in rule and "value" in rule:
                # Conditional assignment
                condition_pattern = re.compile(
                    rule["condition"], flags=0 if case_sensitive else re.IGNORECASE
                )

                def apply_condition(x):
                    if pd.isna(x) or (skip_empty and str(x).strip() == ""):
                        return None
                    if condition_pattern.search(str(x)):
                        return rule["value"]
                    return None

                conditional = source_data.apply(apply_condition)
                values = values.fillna(conditional)

            elif "mapping" in rule:
                # Mapping table
                mapping_dict = rule["mapping"]

                def apply_mapping(x):
                    if pd.isna(x) or (skip_empty and str(x).strip() == ""):
                        return None

                    key = str(x).strip()
                    if not case_sensitive:
                        # Case-insensitive lookup
                        mapping_lower = {k.lower(): v for k, v in mapping_dict.items()}
                        return mapping_lower.get(key.lower())
                    return mapping_dict.get(key)

                mapped = source_data.apply(apply_mapping)
                values = values.fillna(mapped)

        return values

    def _extract_name_part(self, value: Any, part: str) -> Optional[str]:
        """Extract first or last name from a full name."""
        result, _ = self.normalizers["name"].normalize(value)
        return result.get(part)

    def _extract_age_part(self, value: Any, part: str) -> Any:
        """Extract age-related field."""
        result, _ = self.normalizers["age"].normalize(value)
        return result.get(part)

    def _parse_address_column(
        self,
        df: pd.DataFrame,
        source_col: str,
        target_part: str,
        source_config: SourceConfig,
    ) -> pd.Series:
        """Parse combined address field into components."""
        # Check if this source has address parsing configured
        if source_col in source_config.column_map:
            target_action = source_config.column_map[source_col]
            if target_action == "_parse_full_address":
                return df[source_col].apply(
                    lambda x: self.normalizers["address"]
                    .normalize(x)[0]
                    .get(target_part)
                )

        # Default: return as-is for address1, None for others
        if target_part == "address1":
            return df[source_col].apply(self._basic_clean)
        return pd.Series([None] * len(df))

    def _basic_clean(self, value: Any) -> Any:
        """Basic cleaning for string values."""
        if pd.isna(value):
            return None

        if isinstance(value, str):
            # Remove extra whitespace
            cleaned = " ".join(value.split())
            # Return None for empty strings
            return cleaned if cleaned else None

        return value

    def _generate_record_ids(self, df: pd.DataFrame, source_file: Path) -> pd.Series:
        """Generate deterministic record IDs."""
        return pd.Series([f"{source_file.stem}_{i:08d}" for i in range(len(df))])
